### ISSUE TITLE
Fetching Online fails for some titles

### ISSUE THREAD

**Issue by toprak** [MangaManagerORG/Manga-Manager#166]
It sometimes fetch for _goodbye, eri_ it does not fetch for _sayonara, eri_  I use ubuntu 22.04 version is `./MangaManager_23_03_04_64ae3ba_linux`
log:
```Traceback (most recent call last):
  File "tkinter/__init__.py", line 1951, in __call__
  File "src/MetadataManager/MetadataManagerGUI.py", line 444, in process_fetch_online
  File "src/MetadataManager/MetadataManagerLib.py", line 235, in fetch_online
  File "ExternalSources/MetadataSources/Providers/AniList.py", line 112, in get_cinfo
    title_english = data.get("title").get("english").strip() or ""
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'strip'
```

**Comment by majora2007** [comment]
I have reproduced this issue and found the following:

 Fetch Data found title {'romaji': 'Naze Boku no Sekai wo Daremo Oboeteinai no ka?', 'english': None, 'native': 'なぜ僕の世界を誰も覚えていないのか？'}
 
 The series in question on AniList does not have an English name set and thus we fail to write it out. I will adjust the code so that we fallback to at least something set.
