### ISSUE TITLE
Option to change the cover using the <Page Type> field in ComicInfo

### ISSUE THREAD

**Issue by Eljoseto** [MangaManagerORG/Manga-Manager#85]
Currently the ComicInfo metadata accepts the field <pages> that can determine some properties of the page content, But manga manager does not write this field in the XML 

It would be useful to decide the cover image of a comic/manga using the  <Page Type="FrontCover" /> field inside the XML if is present, if not, the cover is just the first image in the CBZ.

Comic tagger lets you make this changes, and writes the Page Type field in the XML
![Captura de pantalla 2022-07-13 121027](https://user-images.githubusercontent.com/29217336/178781124-1acc808b-5269-4260-bdca-2ff55e8a2ca4.png)

**Comment by ThePromidius** [comment]
I'm still curious on the usage of this.
Is there any app that uses this? apart from comicrack or comictagger?

**Comment by ThePromidius** [comment]
ComicInfo was originally used by comicrack which is a library manager/reader but it has been since abandoned.
The only media that might have this field filled are comics.
While the feat might be a good idea there are no aplicable use cases.

Btw Cover Manager looks for a "cover" file name before looking for the first image.
Also i doubt Tachiyomi will ever write comicinfo.xml though that feature might be a good one

**Comment by ThePromidius** [comment]
This will likely not happen. There's no consumer app apart from CR that fills this info or uses it.
